/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface AnthropicConversation {
  id: number;
  title: string;
  createdAt: string;
}

export interface AnthropicMessage {
  id: number;
  conversationId: number;
  role: string;
  content: string;
  createdAt: string;
}

export interface CreateAnthropicConversationBody {
  title: string;
}

export interface SendAnthropicMessageBody {
  content: string;
}

export interface AnthropicConversationWithMessages {
  id: number;
  title: string;
  createdAt: string;
  messages: AnthropicMessage[];
}

export interface AnthropicError {
  error: string;
}

export interface DailyQuestion {
  day: number;
  question: string;
  invitation: string;
}

export interface JournalEntry {
  id: number;
  questionDay: number;
  question: string;
  reflection: string;
  vibration: string;
  createdAt: string;
}

export interface CreateJournalEntryBody {
  questionDay: number;
  question: string;
  reflection: string;
  vibration: string;
}

export interface NewsletterSubscriber {
  id: number;
  email: string;
  name?: string | null;
  createdAt: string;
}

export interface SubscribeNewsletterBody {
  email: string;
  name?: string;
}

export interface NewsletterCount {
  count: number;
}
