/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all conversations
 */
export const ListAnthropicConversationsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListAnthropicConversationsResponse = zod.array(
  ListAnthropicConversationsResponseItem,
);

/**
 * @summary Create a new conversation
 */
export const CreateAnthropicConversationBody = zod.object({
  title: zod.string(),
});

/**
 * @summary Get conversation with messages
 */
export const GetAnthropicConversationParams = zod.object({
  id: zod.coerce.number(),
});

export const GetAnthropicConversationResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.coerce.date(),
  messages: zod.array(
    zod.object({
      id: zod.number(),
      conversationId: zod.number(),
      role: zod.string(),
      content: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Delete a conversation
 */
export const DeleteAnthropicConversationParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List messages in a conversation
 */
export const ListAnthropicMessagesParams = zod.object({
  id: zod.coerce.number(),
});

export const ListAnthropicMessagesResponseItem = zod.object({
  id: zod.number(),
  conversationId: zod.number(),
  role: zod.string(),
  content: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListAnthropicMessagesResponse = zod.array(
  ListAnthropicMessagesResponseItem,
);

/**
 * @summary Send a message and receive an AI response (SSE stream)
 */
export const SendAnthropicMessageParams = zod.object({
  id: zod.coerce.number(),
});

export const SendAnthropicMessageBody = zod.object({
  content: zod.string(),
});

/**
 * @summary Get today's introspective question
 */
export const GetDailyQuestionResponse = zod.object({
  day: zod.number(),
  question: zod.string(),
  invitation: zod.string(),
});

/**
 * @summary List all journal entries (most recent first)
 */
export const ListJournalEntriesResponseItem = zod.object({
  id: zod.number(),
  questionDay: zod.number(),
  question: zod.string(),
  reflection: zod.string(),
  vibration: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListJournalEntriesResponse = zod.array(
  ListJournalEntriesResponseItem,
);

/**
 * @summary Save a new journal reflection
 */
export const CreateJournalEntryBody = zod.object({
  questionDay: zod.number(),
  question: zod.string(),
  reflection: zod.string(),
  vibration: zod.string(),
});

/**
 * @summary Delete a journal entry
 */
export const DeleteJournalEntryParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Subscribe to the Fréquence newsletter
 */
export const SubscribeNewsletterBody = zod.object({
  email: zod.string().email(),
  name: zod.string().optional(),
});

export const SubscribeNewsletterResponse = zod.object({
  id: zod.number(),
  email: zod.string(),
  name: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Get the number of newsletter subscribers
 */
export const GetNewsletterCountResponse = zod.object({
  count: zod.number(),
});
