/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface JournalEntry {
  id: number;
  questionDay: number;
  question: string;
  reflection: string;
  vibration: string;
  createdAt: Date;
}
